name: highlight
version: "2.1.0"
description: >
  Use highlight.js (v9.12.0) as code
  syntax-coloring.
url: http://DLMax.org/statamic-addons/highlight-v2-addon
developer: Max Westen
developer_url: http://DLMax.org
